### ISSUE TITLE
gpt4v dir name in the examples source should be GPT4 instead of GPT4V.

### ISSUE THREAD

**Issue by cvtower** [jam-cc/MMAD#3]
e.g. file evaluation/examples/Transformers/minicpm_query.py +29
from GPT4V.gpt4v import GPT4Query, instruction
should be-> from GPT4.gpt4v import GPT4Query, instruction

since the corresponding dir name is GPT4.

**Comment by jam-cc** [comment]
Thank you for pointing that out. We correct this issue in the  [latest commit](https://github.com/jam-cc/MMAD/commit/94e5218d97083031457adac0118cdd8b8a07f581).
