### ISSUE TITLE
some questions in paper

### ISSUE THREAD

**Issue by xrli-U** [jam-cc/MMAD#5]
Thanks for open source, this is a very promising work.
I have several questions about this paper.
In Fig. 4 (a), IAD Datasets are used to build domain knowledge. Does query image overlap with IAD datasets? Does the retrieved text contain descriptions of all defects in the bottle, or is one description of a specific defect retrieved?

**Comment by jam-cc** [comment]
Thank you for your interest in our work!

1. The IAD dataset does overlap with the query images, as we use it to obtain category-specific text descriptions.

2. The retrieved text contains descriptions of all defects related to the object, as well as a description of the object's normal state.

**Comment by jam-cc** [comment]
Thank you for your question. It's a very interesting point. Currently, we haven't conducted experiments with the query image outside of the IAD dataset. However, we've provided all the domain knowledge used in our study [here](https://github.com/jam-cc/MMAD/blob/main/dataset/MMAD/domain_knowledge.json), which can be used for further research. For example, you could perform cross-experiments using the four types of PCB data from the VisA dataset.
